{
 "title": "Cloudflare — RUM",
 "tags": [
  "cloudflare-workers",
  "cloudflare-metrics",
  "cloudflare-analytics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "RUM Pageloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pageloads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_name) (cf_rum_pageload_visits)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Performance Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_name) (cf_rum_performance_visits)",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  { "title": "Web Vitals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Web Vitals Visits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (host_name) (cf_rum_web_vitals_visits)",
     "legendFormat": "{{host_name}}"
    }
   ]
  }
 ]
}